let productDetails = [
  {name: 'Zacariah', desc: 'Over two thousand years ago in the hills of Judea, there was a man named Zechariah who loved God faithfully and served as a priest in God’s temple. Zechariah and his wife Elizabeth wanted a child, but they were too old. One day, when Zechariah was in the temple burning incense, an angel came to him and told him that he would be blessed with a son and that he should name the baby John. Zechariah was surprised and frightened, and he didn’t believe what the angel said. Immediately, Zechariah was unable to speak. When the baby was finally born, Zechariah asked for a tablet so he could write the baby’s name --John--just as the angel had instructed. At that moment, Zechariah was able to speak again. (Luke 1:5-23,57- 80)'},
  {name: 'Mary', desc: 'Mary was a young Hebrew woman living in Nazareth. She loved the Lord with all her heart. God chose her to be the mother of his one and only son. One day, an angel appeared to Mary and told her that she was going to have a baby. Mary was confused because she was engaged to a man named Joseph but was not yet married. (Luke 1:26-38 )'},
  {name: 'Gabriel', desc: 'Gabriel was the angel that visited both Mary and Zechariah. Gabriel told each of them not to be afraid. He explained to Mary that God had chosen her to bring God’s own son into the world, that the child would reign as a king over His people forever. Mary rejoiced that God had favored her, knowing that this Savior would bless her people forever; that He would create a kingdom which would have no end. (Luke 1:30,46-56)'},
  {name: 'Joseph', desc: 'Mary’s betrothed husband, Joseph, was upset when he learned that Mary was going to have a baby. He loved her very much but couldn’t understand how she was pregnant. He was afraid that she had not been faithful to him. Joseph decided to quietly send Mary away so that she would not be disgraced. (Matthew 1:18-19)'},
  {name: 'Angel of the Lord', desc: 'An angel of the Lord spoke to Joseph in a dream, “Joseph, son of David, do not be afraid to take Mary as your wife; for the Child who has been conceived in her is of the Holy Spirit. She will bear a Son.” Joseph awoke from his sleep and did as the angel of the Lord told him; he took Mary as his wife. (Matthew 1:20-25)'},
  {name: 'Elizabeth', desc: 'Remember Zechariah and his wife, Elizabeth? They both faithfully loved God. Even though everyone thought Elizabeth was too old, she was delighted to learn that she was going to have a baby! She declared, “The Lord has done this for me, He has shown His favor.” Elizabeth and Mary were cousins, even though Elizabeth was much older than Mary. After Gabriel told Mary she would have a son, she traveled about 90 miles to visit Elizabeth. When Mary entered the room, Elizabeth’s baby leapt with joy inside her. Elizabeth marveled that the mother of the Lord should visit her. (Luke 1:36-39)'},
  {name: 'John the Baptist', desc: 'When Zechariah and Elizabeth’s son John grew up, he told people how to know God and how to love Him. John reminded people that they need to ask God to forgive them for their sins. The people called him John the Baptist because he baptized them in the Jordan River. He also answered their questions about scripture and the coming Savior. The prophet Isaiah wrote about John long before John was born, saying that he would be a messenger preparing people to know the Savior. (Matthew 3)'},
  {name: 'Caesar Augustus', desc: 'Nazareth, the town where Mary and Joseph lived, was controlled by the far away Empire of Rome. The Roman Emperor Caesar Augustus wanted to count all of the people who lived under Roman rule so that he could make them pay taxes. Therefore, he issued a decree requiring everyone who lived in the Roman world to go to the town of their ancestors to register for a census. (Luke 2:1-3)'},
  {name: 'Bethlehem', desc: 'Bethlehem is a little town in Judea, a few miles south of Jerusalem. Joseph’s family was from Bethlehem, so Joseph and Mary went there to obey Caesar’s decree to be counted. A little more than one thousand years earlier, Joseph’s ancestor, King David, was born in Bethlehem. The prophet Micah said Bethlehem would be blessed because the Savior of the World would be born there. Bethlehem means “House of Bread,” which is amazing because Jesus calls Himself the “Bread of Life!” (Luke 2:4-5, Micah 5:2 )'},
  {name: 'Manger', desc: 'Mary gave birth to her son in Bethlehem. She wrapped Him in soft cloths, and laid Him in a manger, because there was no room in the inn for Mary and Joseph. God chose not to have the King of Kings born in a fancy castle. Instead, he was born in a lowly place. His bed was a trough where animals drank water. (Luke 2:6-7)'},
  {name: 'Jesus', desc: 'The baby born to Mary was Jesus, the Son of God, the promised Savior of the World.'},
  {name: 'Shepherds', desc: 'In the same region of Bethlehem, shepherds were in the fields watching over their flock by night. Shepherds care for their sheep by feeding them, leading them to water, protecting them from wild animals, and carrying them when they are injured. Jesus cares for all of our needs, protects us from harm, and holds us close to his heart. As the Bible says, Jesus is our good shepherd, and we are his lambs. (Luke 2:8, John 10:11)'},
  {name: 'Angel', desc: 'Suddenly, an Angel of the Lord appeared before the shepherds, and the glory of the Lord shone around them. They were frightened! The angel said to them, “Do not be afraid; for behold, I bring you good news of great joy which will be for all the people; for today in the city of David there has been born for you a Savior, who is Christ the Lord.” (Luke 2:9-12)'},
  {name: 'A Heavenly Host', desc: 'Then a very large number of angels, a heavenly host, appeared with the angel of the Lord and they praised God saying, “Glory to God in the highest, and on Earth peace among men with whom He is pleased.” (Luke 2:14)'},
  {name: 'Sheep', desc: 'shepherds said, “Let us go straight to Bethlehem then, and see this thing that has happened which the Lord has made known to us.” So they left in a hurry, their sheep scurrying behind them, and found way to Mary and Joseph and the baby Jesus as He lay in the manger. The shepherds glorified and praised God for all that they had heard and seen. (Luke 2:15-18)'},
  {name: 'Magi', desc: 'Jesus was born in Bethlehem in the days when Herod was king. After His birth, several Wise Men, or Magi, made their way to Him, following a bright new star in the sky. These Magi were learned men who studied the stars. The Wise Men came from far away in the East to Jerusalem, asking Herod, “Where is He who has been born King of the Jews? For we saw His star in the East and have come to worship Him.” (Matthew 2:1-2)'},
  {name: 'King Herod', desc: 'When King Herod heard this, he and all of Jerusalem were disturbed, for they understood that a very important event was taking place. Gathering all the Jewish chief priests and scribes, Herod asked them where the Messiah was to be born. They replied, “In Bethlehem of Judea; for this is what has been written by the prophet.” (Matthew 2:3-6)'},
  {name: 'Magi', desc: 'Herod found out from the Magi the exact time the special star appeared. Then he sent them to Bethlehem: “Go and search carefully for the Child; and when you find Him, report to me, so that I too may come worship Him.” Herod didn’t really want to worship Jesus. He was afraid Jesus would take his place as King, so he wanted to kill him. (Matthew 2:7-8)'},
  {name: 'Star', desc: 'After speaking with King Herod, the Magi went their way to find Jesus. The star, which they had seen in the East, went on before them until it came and stood over the place where Jesus was. That star was the brightest star they had ever seen. It fulfilled the Bible prophecies about when the Lord of Lords would be born. (Matthew 2:9)'},
  {name: 'Gold', desc: 'When the Wise Men found Jesus held in Mary’s arms, they fell to the ground and worshiped Him. Then, opening their treasures, they presented Him with gifts. One brought gold. Gold is a gift fit for a King. And Jesus is the King of Kings! (Matthew 2:11)'},
  {name: 'Frankincense', desc: 'The second gift was frankincense, a type of very expensive incense made from the sap of a tree. During worship in the temple, the priests burned frankincense, which released a pleasing smell that was an offering to God to atone for our sins. It was likely frankincense that Zechariah burned in the temple. It is a symbol of holiness and righteousness, fitting for Jesus who is holy and righteous—and He is the ultimate sacrificial offering to us from God! (Matthew 2:11)'},
  {name: 'Myrrh', desc: 'The third gift was myrrh. This incense, made from the sap of a thorny bush, was used in the temple for anointing priests, prophets, and kings, and was also used to preserve bodies for burial, and to stop pain. The Wise Men may have understood that Jesus’ life would be difficult, and that he was given a very important job from God. Jesus did go through a lot of pain and suffering, including his own death on the cross. (Matthew 2:11)'},
  {name: 'Wise Men', desc: 'The Wise Men traveled from far away in the East because they knew from charting the stars that a great King was about to be born who would change the entire world! In a dream, God warned the Wise Men not to return to Herod or tell him how to find Jesus. Instead, the Magi left for their own country by another way. (Matthew 2:10)'},
  {name: 'Gift', desc: 'God sent Jesus as the best gift that anyone would ever receive. “For God so loved the world that He gave His one and only son that each and every one of us who believes in Him shall not perish but have eternal life.” ( John 3:16) Jesus gave up his own life because he loves us so much! That means we never have to fear anything! Not even death! Thank you, God, for your very special Christmas gift of Jesus. Let us always treasure Him.'}
]

let cards = document.querySelectorAll('.card')
let img = document.querySelectorAll('.single-img')
let paragraph = document.querySelectorAll('.desc')
let link = document.querySelectorAll('.more-info')

for (let i = 0; i < cards.length; i++) {
  cards[i].addEventListener('click', function (evt) {
    evt.preventDefault()
    console.log(productDetails[i].name)
    console.log(i)
    link[i].style.visbility = 'hidden'
    cards[i].style['max-width'] = '680px'
    cards[i].style['min-width'] = '680px'
    cards[i].style['max-height'] = '650px'
    cards[i].style['min-height'] = '650px'
    img[i].style.margin = '15px'
    paragraph[i].innerHTML = productDetails[i].desc
  })
}
