let productDetails = [
  { name: 'Zecariah', desc: 'Over two thousand years ago in the hills of Judea, there was a man named Zechariah who loved God faithfully and served as a priest in God’s temple. Zechariah and his wife Elizabeth wanted a child, but they were too old. One day, when Zechariah was in the temple burning incense, an angel came to him and told him that he would be blessed with a son and that he should name the baby John. Zechariah was surprised and frightened, and he didn’t believe what the angel said. Immediately, Zechariah was unable to speak. When the baby was finally born, Zechariah asked for a tablet so he could write the baby’s name --John--just as the angel had instructed. At that moment, Zechariah was able to speak again. (Luke 1:5-23,57- 80)', refl: 'What about you? Has God ever surprised you? Why do you think Zechariah did not believe the angel?' },
  { name: 'Mary', desc: 'Mary was a young Hebrew woman living in Nazareth. She loved the Lord with all her heart. God chose her to be the mother of his one and only son. One day, an angel appeared to Mary and told her that she was going to have a baby. Mary was confused because she was engaged to a man named Joseph but was not yet married. (Luke 1:26-38 )', refl: 'What about you? How do you think Mary felt when she found out that she was going to have a baby? You might want to read “Mary’s song” in Luke 1:46-56 to hear Mary’s thoughts when the angel visited her. How would you have reacted?' },
  { name: 'Gabriel', desc: 'Gabriel was the angel that visited both Mary and Zechariah. Gabriel told each of them not to be afraid. He explained to Mary that God had chosen her to bring God’s own son into the world, that the child would reign as a king over His people forever. Mary rejoiced that God had favored her, knowing that this Savior would bless her people forever; that He would create a kingdom which would have no end. (Luke 1:30,46-56)', refl: 'What about you? Have you ever been afraid when something happened that you did not expect? What did you do?' },
  { name: 'Joseph', desc: 'Mary’s betrothed husband, Joseph, was upset when he learned that Mary was going to have a baby. He loved her very much but couldn’t understand how she was pregnant. He was afraid that she had not been faithful to him. Joseph decided to quietly send Mary away so that she would not be disgraced. (Matthew 1:18-19)', refl: 'What about you? Has anyone ever thought that you had done something wrong when you had not? What did you do?' },
  { name: 'Angel of the Lord', desc: 'An angel of the Lord spoke to Joseph in a dream, “Joseph, son of David, do not be afraid to take Mary as your wife; for the Child who has been conceived in her is of the Holy Spirit. She will bear a Son.” Joseph awoke from his sleep and did as the angel of the Lord told him; he took Mary as his wife. (Matthew 1:20-25)', refl: 'What about you? Have you ever been afraid to do something that other people might not understand?' },
  { name: 'Elizabeth', desc: 'Remember Zechariah and his wife, Elizabeth? They both faithfully loved God. Even though everyone thought Elizabeth was too old, she was delighted to learn that she was going to have a baby! She declared, “The Lord has done this for me, He has shown His favor.” Elizabeth and Mary were cousins, even though Elizabeth was much older than Mary. After Gabriel told Mary she would have a son, she traveled about 90 miles to visit Elizabeth. When Mary entered the room, Elizabeth’s baby leapt with joy inside her. Elizabeth marveled that the mother of the Lord should visit her. (Luke 1:36-39)', refl: 'What about you? How do you think Elizabeth felt when she learned she would have a baby in her old age? Why do you think Elizabeth’s baby leapt in her womb?' },
  { name: 'John the Baptist', desc: 'When Zechariah and Elizabeth’s son John grew up, he told people how to know God and how to love Him. John reminded people that they need to ask God to forgive them for their sins. The people called him John the Baptist because he baptized them in the Jordan River. He also answered their questions about scripture and the coming Savior. The prophet Isaiah wrote about John long before John was born, saying that he would be a messenger preparing people to know the Savior. (Matthew 3)', refl: 'What about you? Why do you think John needed to “prepare a way” for the Savior? What would a “Savior” save people from?' },
  { name: 'Caesar Augustus', desc: 'Nazareth, the town where Mary and Joseph lived, was controlled by the far away Empire of Rome. The Roman Emperor Caesar Augustus wanted to count all of the people who lived under Roman rule so that he could make them pay taxes. Therefore, he issued a decree requiring everyone who lived in the Roman world to go to the town of their ancestors to register for a census. (Luke 2:1-3)', refl: 'What about you? How do you think the Jews felt about making a long journey to pay taxes to a foreign Emperor?' },
  { name: 'Bethlehem', desc: 'Bethlehem is a little town in Judea, a few miles south of Jerusalem. Joseph’s family was from Bethlehem, so Joseph and Mary went there to obey Caesar’s decree to be counted. A little more than one thousand years earlier, Joseph’s ancestor, King David, was born in Bethlehem. The prophet Micah said Bethlehem would be blessed because the Savior of the World would be born there. Bethlehem means “House of Bread,” which is amazing because Jesus calls Himself the “Bread of Life!” (Luke 2:4-5, Micah 5:2 )', refl: 'What about you? What do you think “Bread of Life” means?' },
  { name: 'Manger', desc: 'Mary gave birth to her son in Bethlehem. She wrapped Him in soft cloths, and laid Him in a manger, because there was no room in the inn for Mary and Joseph. God chose not to have the King of Kings born in a fancy castle. Instead, he was born in a lowly place. His bed was a trough where animals drank water. (Luke 2:6-7)', refl: 'What about you? Were you surprised that God’s son was not born in a palace? Why do you think God wanted him to be born in a humble place?' },
  { name: 'Jesus', desc: 'The baby born to Mary was Jesus, the Son of God, the promised Savior of the World.', refl: 'What about you? Do you think people were surprised that a baby could be the Savior of the World?' },
  { name: 'Shepherds', desc: 'In the same region of Bethlehem, shepherds were in the fields watching over their flock by night. Shepherds care for their sheep by feeding them, leading them to water, protecting them from wild animals, and carrying them when they are injured. Jesus cares for all of our needs, protects us from harm, and holds us close to his heart. As the Bible says, Jesus is our good shepherd, and we are his lambs. (Luke 2:8, John 10:11)', refl: 'What about you? How does Jesus take care of you?' },
  { name: 'Angel', desc: 'Suddenly, an Angel of the Lord appeared before the shepherds, and the glory of the Lord shone around them. They were frightened! The angel said to them, “Do not be afraid; for behold, I bring you good news of great joy which will be for all the people; for today in the city of David there has been born for you a Savior, who is Christ the Lord.” (Luke 2:9-12)', refl: 'What about you? Would you be frightened if you saw an angel?' },
  { name: 'A Heavenly Host', desc: 'Then a very large number of angels, a heavenly host, appeared with the angel of the Lord and they praised God saying, “Glory to God in the highest, and on Earth peace among men with whom He is pleased.” (Luke 2:14)', refl: 'What about you? Do you think God is pleased with you? What pleases God?' },
  { name: 'Sheep', desc: 'shepherds said, “Let us go straight to Bethlehem then, and see this thing that has happened which the Lord has made known to us.” So they left in a hurry, their sheep scurrying behind them, and found way to Mary and Joseph and the baby Jesus as He lay in the manger. The shepherds glorified and praised God for all that they had heard and seen. (Luke 2:15-18)', refl: 'What about you? Would you have left to search for the baby? Why?' },
  { name: 'Magi', desc: 'Jesus was born in Bethlehem in the days when Herod was king. After His birth, several Wise Men, or Magi, made their way to Him, following a bright new star in the sky. These Magi were learned men who studied the stars. The Wise Men came from far away in the East to Jerusalem, asking Herod, “Where is He who has been born King of the Jews? For we saw His star in the East and have come to worship Him.” (Matthew 2:1-2)', refl: 'What about you? How do you think the Wise Men found out about this exciting birth?' },
  { name: 'King Herod', desc: 'When King Herod heard this, he and all of Jerusalem were disturbed, for they understood that a very important event was taking place. Gathering all the Jewish chief priests and scribes, Herod asked them where the Messiah was to be born. They replied, “In Bethlehem of Judea; for this is what has been written by the prophet.” (Matthew 2:3-6)', refl: 'What about you? Why do you think King Herod wanted to know where Jesus was born?' },
  { name: 'Magi', desc: 'Herod found out from the Magi the exact time the special star appeared. Then he sent them to Bethlehem: “Go and search carefully for the Child; and when you find Him, report to me, so that I too may come worship Him.” Herod didn’t really want to worship Jesus. He was afraid Jesus would take his place as King, so he wanted to kill him. (Matthew 2:7-8)', refl: 'What about you? Has someone ever asked you to do something that you didn’t want to do? That made you feel uncomfortable?' },
  { name: 'Star', desc: 'After speaking with King Herod, the Magi went their way to find Jesus. The star, which they had seen in the East, went on before them until it came and stood over the place where Jesus was. That star was the brightest star they had ever seen. It fulfilled the Bible prophecies about when the Lord of Lords would be born. (Matthew 2:9)', refl: 'What about you? What do you think of when you see a sky full of stars?' },
  { name: 'Gold', desc: 'When the Wise Men found Jesus held in Mary’s arms, they fell to the ground and worshiped Him. Then, opening their treasures, they presented Him with gifts. One brought gold. Gold is a gift fit for a King. And Jesus is the King of Kings! (Matthew 2:11)', refl: 'What about you? Do you like to receive Christmas gifts? What is one of your favorite Christmas gifts?' },
  { name: 'Frankincense', desc: 'The second gift was frankincense, a type of very expensive incense made from the sap of a tree. During worship in the temple, the priests burned frankincense, which released a pleasing smell that was an offering to God to atone for our sins. It was likely frankincense that Zechariah burned in the temple. It is a symbol of holiness and righteousness, fitting for Jesus who is holy and righteous—and He is the ultimate sacrificial offering to us from God! (Matthew 2:11)', refl: 'What about you? Scrape your fingernail in the frankincense. How does it smell?' },
  { name: 'Myrrh', desc: 'The third gift was myrrh. This incense, made from the sap of a thorny bush, was used in the temple for anointing priests, prophets, and kings, and was also used to preserve bodies for burial, and to stop pain. The Wise Men may have understood that Jesus’ life would be difficult, and that he was given a very important job from God. Jesus did go through a lot of pain and suffering, including his own death on the cross. (Matthew 2:11)', refl: 'What about you? Have you ever been in a lot of pain? Did you wish you could make the pain go away?' },
  { name: 'Wise Men', desc: 'The Wise Men traveled from far away in the East because they knew from charting the stars that a great King was about to be born who would change the entire world! In a dream, God warned the Wise Men not to return to Herod or tell him how to find Jesus. Instead, the Magi left for their own country by another way. (Matthew 2:10)', refl: 'What about you? Would you have had the courage to disobey King Herod?' },
  { name: 'Gift', desc: 'God sent Jesus as the best gift that anyone would ever receive. “For God so loved the world that He gave His one and only son that each and every one of us who believes in Him shall not perish but have eternal life.” ( John 3:16) Jesus gave up his own life because he loves us so much! That means we never have to fear anything! Not even death! Thank you, God, for your very special Christmas gift of Jesus. Let us always treasure Him.', refl: 'What about you? Would you like to receive Jesus as a gift?' }
]

let goDeeper = [
  { deeper: 'Once a year, on the most solemn of all Israelite holidays, the Day of Atonement (or Yom Kippur), a priest was chosen to perform special rituals to atone for the sins of the people. The year before Jesus’ birth, the priest Zachariah was chosen to perform this ritual. He burned incense in a special part of God’s Temple called the Holy of Holies (the sacred area in the Temple where God dwelt. The Ark of the Covenant had been kept there before it disappeared during the reign of Babylon’s King Nebuchadnezzar.) This is what the Ark of the Covenant may have looked like. It contained the tablets listing the Ten Commandments God gave to Moses, the staff of the first High Priest Aaron (Moses’ brother,) and a golden bowl of manna, which was a special food the Hebrews ate while they wandered in the desert for forty years.' },
  { deeper: 'The Bible tells us that both Elizabeth and Zechariah were descendents of Moses’ brother, Aaron. God called Aaron to help Moses, and Aaron became the very first High Priest of the Jewish people. Aaron’s family continued to serve as priests to God. The clothes of the priests were special and filled with meaning. They wore an “ephod” and a chest piece that contained twelve precious stones. Each stone represented one of the twelve tribes of Israel (each tribe was named after one of Jacob’s sons). On each shoulder of the ephod sat a piece of onyx, carved with the names of the twelve tribes. The best tailors embroidered the ephod with gold thread as well as blue, purple and scarlet yarn. Bells made of gold and pomegranates made of wool hung from the bottom of the robe. The bells would make a noise as the priests moved around the Holy of Holies, making an offering of incense to God. Exodus 28 records God’s very specific instructions on how to make the ephod, all of the priestly garments, and the Ark of the Covenant.' },
  { deeper: 'The Bible tells us that John the Baptist wore a leather belt, and that his clothes were made from camels hair (like the Old Testament prophet Elijah). It also tells us that he had some odd eating habits; he ate locusts and honey!' },
  { deeper: 'The Caesar Augustus figure is modeled from the “Augustus Prima Porta statue that is at the Vatican Museum in Rome, Italy. Archeologists found the original statue in Primo Porta, just outside of Rome. Augustus’ wife, Livia Drusilla, was living there in a villa following her husband’s death. The statue is believed to have been sculpted around the time Jesus lived. Caesar Augustu’s Great Uncle was Julius Caesar, who adopted him as his son and heir. When Julius Caesar was murdered, Augustus vied with Cleopatra and Marc Antony to become the Emperor of Rome.' },
  { deeper: 'Jesus tells us that He is “the bread of life.” He said that “Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty” (John 6:35). Jesus said these words just after he multiplied loaves of bread and fish to feed a huge crowd of people. He meant that if you follow Him, you will be fed with something even better than bread made of wheat or grain. You may want to read John chapter 6 to understand more.' },
  { deeper: 'Most likely, the manger Jesus slept in was not made out wood as we often see in manger scenes, because wood was scarce in Israel. Instead, it was likely carved out of stone, which was plentiful. It is interesting that Jesus started His earthly life in a borrowed stone manger, wrapped in cloth. Similarly, He ended His earthly life buried in a borrowed stone tomb. After his death, His disciple Joseph of Arimathea, took Jesus’ body, wrapped it in a clean linen cloth, and laid it in Joseph’s new tomb which he had hewn out of rock. (Luke 23:50-53)' },
  { deeper: 'What are Angels? What does the bible tell us about them? Psalm 91 tells us that if you believe in God, He will order his angels to protect you wherever you go. When King David wrote Psalm 103, he said that angels were mighty ones who carry out God’s plans, who listen for each of His commands, who serve Him and do His will.' },
  { deeper: 'How do we please God? Several years after Jesus died, the apostle Paul wrote a letter to his Roman friends. He told them that because God is so loving and kind to us, we should offer our ordinary lives to Him every day. We should set apart all we have and do and give it to God as an offering. That would please to Him. Read Romans 12:1 to find out more about what Paul told his friends.' },
  { deeper: 'King Herod’s image is taken from a coin minted during his son’s reign. Historians believe Herod the Great was born about 74 B.C. and died just a few years after Jesus was born. He was a smart diplomat who pleased the leadership in Rome. The Roman Senate appointed Herod King of Judea and he built enormous public buildings, fortresses, aqueducts and ampitheaters. He also rebuilt the Temple where Jesus prayed. Herod was a brutal dictator who killed his father-in-law, several of his wives and even killed three of his own sons! He was so cruel, Caesar Augustus said, “It is better to be Herod’s pig than his son.”' },
  { deeper: 'How did the Wise Men know where to go? The Bible tells us that “A star will come out of Jacob” (Numbers 24:7) —meaning one of Jacob’s descendents will rise and lead us all. Jesus was a descendant of Jacob! The Wise Men may have read the Old Testament prophecies and been drawn to follow the bright star in the sky. Isaiah 60:1 says, “Rise up and shine, for your light has come. The shining-greatness of the Lord has risen upon you.” Isaiah continues, “And the Gentiles shall come to thy light, and kings to the brightness of thy light.” (Isaiah 60:3)' },
  { deeper: 'Who were the Wise Men? How do we know what they brought? The book of Isaiah, written about 700 years before Jesus was born, tells us “The wealth of the gentiles shall come to you. Great caravans of camels will come, from Midian and Ephah. They will come from Sheba, bringing gold and incense. People will tell the good news of what the Lord has done!” (Isaiah 60:5-6) From this we know that the Wise Men came from an area that is now known as Saudi Arabia (Midian and Ephah) and either Yemen, or possibly Ethiopia (Sheba). Isaiah tells us “they shall bring gold and incense.” Matthew confirms that they brought gold and incense, telling us what type of incense (frankincense and myrrh). The Bible doesn’t tell us how many Wise Men came, or how soon after Jesus’ birth they arrived, but we do know that they brought three gifts and that Mary and Joseph and Jesus were living in a house when they came.' }
]

let button = document.querySelectorAll('button')
var modal = document.getElementById('myModal')
var span = document.getElementsByClassName('close')[0]
let deeper = document.querySelector('.deeper')

let cards = document.querySelectorAll('.card')
let paragraph = document.querySelectorAll('.desc')
let link = document.querySelectorAll('.more-info')
let reflection = document.querySelectorAll('.refl')

for (let i = 0; i < button.length; i++) {
  button[i].addEventListener('click', function (evt) {
    evt.preventDefault()
    console.log('button is working')
    modal.style.display = 'block'
    deeper.innerHTML = goDeeper[i].deeper
  })
}

span.onclick = function () {
  modal.style.display = 'none'
}

window.onclick = function (event) {
  if (event.target === modal) {
    modal.style.display = 'none'
  }
}

for (let i = 0; i < cards.length; i++) {
  cards[i].addEventListener('click', function (evt) {
    evt.preventDefault()
    if (cards[i].classList.contains('cards-on-click')) {
      link[i].style.visibility = 'visible'
      cards[i].classList.remove('cards-on-click')
      paragraph[i].innerHTML = ''
      reflection[i].innerHTML = ''
    } else {
      link[i].style.visibility = 'hidden'
      cards[i].classList.add('cards-on-click')
      paragraph[i].innerHTML = productDetails[i].desc
      reflection[i].innerHTML = productDetails[i].refl
    }
  })
}
